### PR TITLE
Quality of Life options for TomlTable and TomlValue

### LINKED ISSUE #27: Quality of Life Functions for TomlTable and TomlValue
It would be nice if TomlTable implemented IEnumerable so you could iterate on the table directly (expected behavior) instead of having to grab the Entries property.

Additionally, all TomlProperties should return the value in "StringValue" when ToString is called on the object (expected behavior).

### PR DESCRIPTION
**Pull request by johnkiddjr**
Fixes #27 

This adds the functionality of IEnumerator to TomlTable, allowing you to iterate on the table without needing to reference the Entries property.

```
foreach (var item in table.Entries)
{
    ...
}
```

Becomes

```
foreach (var item in table)
{
    ...
}
```

This also adds an override on the ToString method for TomlValue to return the StringValue property.

```
TomlString stringValue; //or any other TomlValue
Console.WriteLine(stringValue.StringValue);
```

Becomes

```
TomlString stringValue; //or any other TomlValue
Console.WriteLine(stringValue.ToString()); // outputs the value of StringValue now
```

### CODE REVIEW

**Comment by SamboyCoding** [comment]
I have no issues with the actual content of this pull request, so on that front, this is approved, but as per coveralls' comment above, the lack of unit tests for the enumeration and string values has resulted in coverage decreasing, which I'd rather avoid, if you wouldn't mind writing a couple tests to cover those cases -- though they really don't need it, it's easier to just enforce the rule of "test as high a percentage of the codebase as possible" rather than making case-by-case decisions.

**Comment by johnkiddjr** [comment]
Agreed, added tests to ensure ToString and StringValue are equal (done for both TomlString and TomlLong) and tests to check that iterated values are the same as values pulled directly from the dictionary.

**Comment by SamboyCoding** [comment]
Appreciate it! Assuming this CI run passes fine, I'll merge this then.

**Review by SamboyCoding — APPROVED** [review]

**Comment by SamboyCoding** [comment]
Right well the explicit interface implementation wasn't covered but I can live with that, merging.

**Pull request merged**
